### ISSUE TITLE
Implement "Log something only once (or only N times)" feature

### ISSUE THREAD

**Issue by zsabbagh** [Glace97/loguru#1]
Chosen issue is [Log N-times feature](https://github.com/Delgan/loguru/issues/383). This is the main task of our Assignment

- [x] **Before any changes to code:** Run regression tests and store the results.  - Glacier, now [added to our own repo](https://github.com/zsabbagh/dd2480-assignment-4/blob/main/PRE_regression_tests)
- [x] **Before any changes to code:** Check and store code coverage data. (**Note**, results from the task above does not include branch coverage in coverage report)
- [x] Implement the function `limit` for the class `Logger` in "loguru/_logger.py" (see discussion on chosen issue for context).
   - Parameters: 
     - `number` - Integer. The limit of how often the logger will log the message
     - `overflow_msg` (optional) - String. After limit has been reached, `overflow_msg` gets printed instead (once, not multiple times). Example: `logger.limit(1, overflow_msg="testing").info("Suppressing future io errors")`.
- [x] Rerun regression tests and see if something is broken after implementing `limit`
- [x] Implement tests for `limit`. (Unit and/or integration?)
- [x] Check and store code coverage data after changes.

**Comment by Glace97** [comment]
Me and Einar have discussed the following idea:
- Create a new class parameter for Logger called `time_limit `and `limit_info ` which is default set to `None`
- limit function: 
    - takes in parameters` frequency_limit`, `minutes `and `overflow_msg`
    - Returns a new instance of Logger (like opt does)
        - Sets time_limit to an instance of datetime
        - Sets limit_info to a dictionary {“minutes”: minutes, “frequency_limit”: frequency, “overflow_msg”: overflow_msg}
- `_log `function update
    - Check if the limit_info is set, if it is not None then do the following:
    - Check if time_limit has been exceeded by minutes by checking ` now - time_limit`
        - If it has been exceeded, reset time_limit and limit_info
        - Else, do nothing
    - Check if log msg exists in limit_info dict
        - case 1; message is not in the hashmap --> add to it the message as key and counter 1 as value (”test log message” : 1)
        - case 2; message is in limit_info but `counter < frequency_limit `--> increment `counter`
        - case 3: `counter == frequency_limit `--> print one last time, and print limit_info["overflow_msg"]
        - case 4: the message is in limit_info and counter > frequency --> don't print anything, we have exceeded the limit
  
  We would need to further clarify requirements of `limit()`.
  -  (”test log message” : 1) --> this is stored in limit_info_dict, does this mean that we have a key-value pair/tuple in   `limit_info `, which specifies what message we will supress after a certain limit?
  

 Suggestion/adjustment: We could have an input variable which is the message that is to be suppressed after a given limit, and this one is stored with counter = 0 at initialization, as 4th element in `limit_info` .
 **This would assume the requirement that the `limit()` function is used on specific logs, determined by the user.**
 
 Edit: Motivation for adding the changes to `_log` is due to `warning`, `success`, `info` etc, all calls `_log`

**Comment by Glace97** [comment]
The commit above is a naive approach, on separate branch` `1-implement-limit-first-approach``.
Simple example of usage would be:

```
once_logger = logger.limit(1, 60, "Will not print out more warnings.")
for i in range(10):
        once_logger.warning("Logging a warning! Should not print this more than once.")
```

The implementation breaks a lot of the existing tests and is not feasible at all in its current form.

**Comment by Glace97** [comment]
Old tests now work on commit [66533ee](https://github.com/Glace97/loguru/commit/66533ee75347a21eafd4d8d691429388b61e90b0):
Todo: 
- Add new tests for new functionality
- Change `time` parameter to correspond to minutes (atm seconds) 
- Fix trailing whitespace and other `pylint` issues
